import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import Link from "next/link";
import '../styles/login.module.css'
// app/layout.js or layout.tsx
import 'bootstrap/dist/css/bootstrap.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Navbar */}
        {/* <nav style={{ padding: "1rem", backgroundColor: "black" }}>
          <Link href="/" style={{ marginRight: "1rem" }}>Home</Link>
          <Link href="/dashboard">Dashboard</Link>
        </nav> */}

        {/* Main Content */}
        <main style={{ minHeight: "100vh", padding: "0rem" }}>
          {children}
        </main>

        {/* Footer */}
        {/* <footer style={{ textAlign: "center", padding: "1rem", backgroundColor: "#f0f0f0" }}>
          <p>&copy; 2025 My Next App</p>
        </footer> */}
      </body>
    </html>
  );
}
